---
title: "Project Description"
author: "Neal Marquez"
date: "October 25, 2017"
output: html_document
---

## Project Proposal
Since the turn of the century there has been an increase in minority representation in higher education in the United States, with most minority groups having a higher percentage of their high school graduating age demographic attending college in comparison to the 20th century. Despite this many universities have difficulty making their minority students feel as integrated into the community, resulting in the development of multiple campus specific organizations whose goal is to make minority students feel more welcome. I argue that because minority students feel that institutions of higher education, especially prestigious institutes, may not capture a culture of their own, that they may be less inclined to pursue or feel less comfortable navigating the rhetoric of these institutions. To test this we look at how rates of acceptance into a prestigious set of schools in California, the UC system, has differed for hispanic students based on whether the population of the high school that they originate is largely made up of white students.

## Data Sources
Data come from two sources. Admission into UC schools is taken from the online UC data portal and is broken down by ethnic group such that there is yearly reporting of number of applicants, admissions, and acceptances for each UC as well as UC as a whole for each high school in California. The High School demographic data comes from a list of static files hosted by the California Department of Education and is updated annually for the year prior. Information includes the counts of students in the graduating class by ethnic group as well as the counts for students who are UC eligible.

The outcome for this analysis will be the number of hispanic students admitted to the UC system by school and year. The covariate that we will adjust for is the proportion of the students who are white which varies annually. Because this is a count model we will need to adjust for the number of senior hispanic students for every school in each year.

## Data Variety
Data is collected on 705 individual schools for years between 1994-2015. Not all data is complete as not all high schools had recorded information on the ethnic composition of their school to the Department of Education. Measurement occasions are fixed as school admittances happen yearly in the same three month range.


## Random Sample Plot
```{r warning=F}
library(ggplot2)
hisp_subset <- read.csv("./subset_data.csv")
ggplot(hisp_subset, aes(x=year, y=uc_addmitted/count, color=demo_comp)) + 
    geom_point() + 
    geom_smooth(method="lm", se=F) +
    facet_wrap(~school) + 
    labs(title="Linear Model Trajectories of Hispanic Student Admission") + 
    ylim(0,1) + ylab("UC Admission / HS Pop Count") + xlab("Year") +
    labs(color="Demographic \nComposition")
```
